### ISSUE TITLE
(Info) Expanded frequency range 

### ISSUE THREAD

**Issue by alphafox02** [racerxdl/lms_tcp#2]
Working great on a Pi4 aarch64 Ubuntu. Just out of curiosity, would it be more on GQRX to open up the available frequency range of their “rtl_tcp” option? I could only go up to 1.7 GHz when connecting to the lms_tcp but it works really well otherwise. 

Thank you for putting this together.

**Comment by racerxdl** [comment]
Hi @alphafox02, I think that's a limitation of the gr-osmosdr plugin. https://github.com/osmocom/gr-osmosdr/blob/master/lib/rtl_tcp/rtl_tcp_source_c.cc#L431-L447

It might be possible to switch to a unknown value, which would make gr-osmosdr to think its a E4000, which the range goes up to 2.2GHz.

If you compiled it locally, you can change it here: https://github.com/racerxdl/lms_tcp/blob/main/cmd/lms_tcp.go#L104

to:

```go
TunerType:      rtltcp.RtlsdrTunerE4000,
```

**Comment by alphafox02** [comment]
Awesome, that’s a great idea. I’ll test it out and report back. Too bad you lose some of the lower range. Maybe they’ll update gr-osmosdr and insert a new type.

**Comment by racerxdl** [comment]
I'm planning on doing a proper server for limesdr, then I can add support on gr-osmosdr ^^

**Comment by alphafox02** [comment]
Even better! Is there any, I guess you’d say optimization on lms_tcp vs rtl_tcp? I’ve always heard that spy server somehow was better about the amount of bandwidth it needed to send the info back to the server vs rtl_tcp.

**Comment by racerxdl** [comment]
Well rtl_tcp is made in go which _should_ reduce some CPU usage, but I really not sure. About the bandwidth, will be basically the same since the format over network is the same.

Spyserver does a bit different for SDR# only, it sends a FFT of the spectrum separated from the I/Q itself. Then if you need only, let's say, 25kHz for a NBFM demod, the spyserver itself will make a 25kHz I/Q from the frequency you want, and _only_ send that I/Q but the full FFT. 

This increases the CPU Usage in server side, but *drastically* reduces the network bandwidth.

I did a similar project called [radioserver](https://github.com/racerxdl/radioserver) but I plan to re-factor some stuff since the cpu usage was quite high.

**Comment by alphafox02** [comment]
The E4000 modification worked perfectly. Now it’s allowing for the slightly higher frequency range.

**Comment by alphafox02** [comment]
@racerxdl Just a small note, SDR++ has a rtl-tcp module built in and so I gave it a go with lms_tcp. It currently has no left and right limits so I was able to actually tune lms_tcp outside the available range of the LimeSDR. Just curious, can hardware limits be built into lms_tcp itself?
